// Bypass SSL validation for Aiven (Self-Signed Certs)
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const { Client } = require('pg');

// Use environment variable for safety
const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("❌ Error: DATABASE_URL environment variable is missing.");
  console.error("   Run with: set DATABASE_URL=... && node scripts/seed_followup.js");
  process.exit(1);
}

const client = new Client({
  connectionString: connectionString,
  ssl: {
    rejectUnauthorized: false,
  },
});

const query = `
INSERT INTO follow_ups (user_id, context, notify_at, status)
VALUES (
  'test-user-script', 
  'This is your test reminder generated by the script!', 
  NOW() - INTERVAL '1 minute', 
  'pending'
);
`;

async function main() {
  console.log('Connecting to Aiven PostgreSQL...');
  try {
    await client.connect();
    console.log('Connected successfully.');
    
    console.log('Inserting Test Record...');
    await client.query(query);
    console.log('✅ Test record inserted! A pending follow-up is now overdue.');
    
  } catch (err) {
    console.error('❌ Error seeding data:', err);
  } finally {
    await client.end();
    console.log('Disconnected.');
  }
}

main();
